spring.application.name=templateproject

#encoding set UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

# ??? ?? ?? ????.
spring.mustache.prefix=file:src/main/resources/templates/
spring.mustache.suffix=.mustache
spring.mustache.cache=false
